logging:
  level:
    org:
      springframework: INFO

server:
  port: 8080
  servlet:
    context-path: /spring-demo
    session:
      cookie:
        name: spring_demo
  jetty:
    accesslog:
      enabled: true
      file-date-format: .yyyyMMdd
      filename: /tmp/logs/spring-demo.jetty.access.log
      custom-format: "%{client}a - %u %{yyyy-MM-dd HH:mm:ss.SSS|Asia/Shanghai}t %r %s %O"
      append: true